.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "STARDOG_NAMESPACE_ADD" "1" "August 2014" "Clark & Parsia" "stardog"
.
.SH "NAME"
\fBstardog_namespace_add\fR \- Adds a new namespace prefix in the database, overriding any previous mapping for the prefix\.
.
.SH "SYNOPSIS"
\fBstardog\fR \fBnamespace\fR \fBadd\fR [ {\-p | \-\-passwd} \fIpassword\fR ] [ {\-P | \-\-ask\-password} ] \-\-prefix \fIprefix\fR [ {\-u | \-\-username} \fIusername\fR ] \-\-uri \fInamespace\fR [ {\-v | \-\-verbose} ] [\-\-] \fIdatabase\fR
.
.SH "OPTIONS"
.
.TP
\fB\-p\fR \fIpassword\fR, \fB\-\-passwd\fR \fIpassword\fR
Password\.
.
.TP
\fB\-P\fR, \fB\-\-ask\-password\fR
Prompt for password\.
.
.TP
\fB\-\-prefix\fR \fIprefix\fR
Namespace prefix to be added\.
.
.TP
\fB\-u\fR \fIusername\fR, \fB\-\-username\fR \fIusername\fR
User name\.
.
.TP
\fB\-\-uri\fR \fInamespace\fR
Namespace URI to be added\.
.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Verbose flag that causes more detailed information to be printed
.
.TP
\-\-
This option can be used to separate command\-line options from the list of arguments (useful when arguments might be mistaken for command\-line options)\.
.
.TP
\fIdatabase\fR
The name of the database or the full connection string of the database to connect to\. If only the name is provided, the default server URL will be pre\-pended to the name of the database in order to construct the connection string\. Connection parameters such as \';reasoning=QL\' can be included in the provided database name\. Connection parameters specified like this can be overridden by specific options on the command\. The default server URL will be read from the JVM argument \'stardog\.default\.cli\.server\'\. If the JVM argument is not set, the default value \'snarl://localhost:5820\' is used\. If the server URL has no explicit port value, the default port value \'5820\' is used\. To use a secure connection, you should specify the full connection string and postfix \'s\' to the protocol, e\.g\. snarls or https\.

