.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "STARDOG\-ADMIN_DB_ONLINE" "8" "August 2014" "Clark & Parsia" "stardog-admin"
.
.SH "NAME"
\fBstardog\-admin_db_online\fR \- Brings a database online\.
.
.SH "SYNOPSIS"
\fBstardog\-admin\fR [ \-\-server \fIserver url\fR ] \fBdb\fR \fBonline\fR [ {\-p | \-\-passwd} \fIpassword\fR ] [ {\-P | \-\-ask\-password} ] [ {\-u | \-\-username} \fIusername\fR ] [ {\-v | \-\-verbose} ] [\-\-] \fIdatabase\fR
.
.SH "OPTIONS"
.
.TP
\fB\-p\fR \fIpassword\fR, \fB\-\-passwd\fR \fIpassword\fR
Password\.
.
.TP
\fB\-P\fR, \fB\-\-ask\-password\fR
Prompt for password\.
.
.TP
\fB\-\-server\fR \fIserver url\fR
URL of Stardog Server\. If this option isn\'t specified, it will be read from JVM argument \'stardog\.default\.cli\.server\'\. If the JVM arg isn\'t set, the default value \'snarl://localhost:5820\' is used\. If server URL has no explicit port value, the default port value \'5820\' is used\. Example: \'stardog \-\-server snarl://12\.34\.56\.78:5820 server stop\'
.
.TP
\fB\-u\fR \fIusername\fR, \fB\-\-username\fR \fIusername\fR
User name\.
.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Verbose flag that causes more detailed information to be printed
.
.TP
\-\-
This option can be used to separate command\-line options from the list of arguments (useful when arguments might be mistaken for command\-line options)\.
.
.TP
\fIdatabase\fR
The name of the database for the operation
.
.SH "DISCUSSION"
Brings an offline database back online so that it can accept connections\. Bringing a database online can be expensive depending on how large the database is and what, if any, housekeeping needs to be done in order to get the database ready to handle connections\.
.
.SH "EXAMPLES"
.
.TP
Bring the database \'foo\' online:
$ stardog\-admin db online foo

